valor = input('Digite algo: ')
print('o tipo primitivo desse valor é',type(valor),'tendeu bichuba')
print('Só contem espaços?  ',valor.isspace  ())
print('É numerico?         ',valor.isnumeric())
print('É alfabético?       ',valor.isalpha  ())
print('Está em maiúsculas? ',valor.isupper  ())
print('Está em minúsculas? ',valor.islower  ())
print('É alfanumerico?     ',valor.isalnum  ())
print('Está capitalizado?  ',valor.istitle  ())
